### ISSUE TITLE
FR: Support multiple prices for a single feature, based on interval

### ISSUE THREAD

**Issue by jevon** [tierrun/tier#121]
### What are you trying to do?

SaaS pricing often allows for a discount for longer billing terms. 

Tier currently supports an **interval** for a plan's price. 

Tier should support multiple intervals for a single plan, each with their own corresponding price. 

### How should we solve this?

Stripe supports multiple prices per product. This is different from multi-currency prices. 

[From Stripe docs](https://stripe.com/docs/products-prices/getting-started#multiple-products-and-prices): 

> Create multiple prices for a single product if you’re selling the same item at different price points. For example, **if you offer a subscription tier at monthly and yearly rates**, create one product for the tier and one price for the monthly rate and another for the yearly rate. 

### What is the impact of not solving this?

Annual pricing is very prevalent and often one of the first things vendors seem to want to do to adjust their pricing. 

It is one of the first things you see recommended as you look at ways to improve pricing. 

### Anything else?

This should be implemented before #119 as it may impact the implementation of that feature.

**Comment by bmizerany** [comment]
In the recent past, we discussed trying fancy things in pricing.json but ultimately kept ending up at a) use a loop/list compression to generate these b) do (a) in the WYSIWYG, or c) copy and paste a plan by hand and give it a new name like `plan:pro:yearly@1`.

It might be worth considering some syntax in the plan name that automatically implies the interval, but that might get tricky/confusing if the interval is set and the interval in the name does not match. However, we could make it an error if named incorrectly.

If we do go down the path, I would argue we lean in and require the interval to be in the name and not imply any defaults.

However, it could be a slippery slope considering currency and thinking about it the same way.

I'd like to spend a little time with #119 before jumping into this. There may be a way that already exists as things are today and fixing #119 might be a documentation issue, and/or a small change to Tier. I'm just not familiar enough with Stripe Payment Links ATM to know how best to proceed here yet.

I'll this ticket updated as my research progresses.

**Comment by bmizerany** [comment]
Also: Do we automatically update the Title for the price as well? (e.g. `Convert Pro (Monthly) - Temperature`)

**Comment by jevon** [comment]
https://stripe.com/docs/billing/subscriptions/multiple-products#restrictions

Posting this as I think it adds ambiguity to the decision.
