### ISSUE TITLE
FR: Docs / support for serverless and edge SDK

### ISSUE THREAD

**Issue by itsezc** [tierrun/tier#136]
### What are you trying to do?

Trying to use Tier in a serverless environment more specifically Cloudflare workers, currently this doesn't seem possible or isn't documented, with the increasing usage of edge runtimes it makes sense to support these out of the box

### How should we solve this?

Create another SDK for serverless / edge platforms like Cloudflare workers, or document the current SDK to highlight the environments its supported on with relevant docs (would be happy to help with this if necessary).

### What is the impact of not solving this?

Cannot use Tier as I would have to setup alot of infrastructure around supporting this i.e. having to run a node specifically to run the node SDK, managing its security and adds complexity to architecture.

**Comment by isaacs** [comment]
@itsezc Can you run the JS SDK in [raw client mode](https://github.com/tierrun/node-sdk#raw-client-mode)?

Ie, you would have to spin up a sidecar service, but you can then `import { Tier } from 'tier/client'` and then instantiate the object as shown, which should work in any JS environment that has `fetch()`.

Could definitely benefit from a specific tutorial or example using CF workers in our docs or blog, of course.

**Comment by isaacs** [comment]
Or, if you prefer:

```js
import { Tier } from 'https://unpkg.com/tier@^3.1.0/lib/client.js'
```

**Comment by itsezc** [comment]
> @itsezc Can you run the JS SDK in [raw client mode](https://github.com/tierrun/node-sdk#raw-client-mode)?
> 
> Ie, you would have to spin up a sidecar service, but you can then `import { Tier } from 'tier/client'` and then instantiate the object as shown, which should work in any JS environment that has `fetch()`.
> 
> Could definitely benefit from a specific tutorial or example using CF workers in our docs or blog, of course.

I've got Tier SDK running on CF workers successfully (with Wrangler 2) and on Bun 0.2.2 but a tutorial / guide would be amazing indeed!
