### ISSUE TITLE
Bug: JSON schema references

### ISSUE THREAD

**Issue by itsezc** [tierrun/tier#139]
### What is the issue?

When using the JSON Schema in VSCode the following error is thrown:

```
Problems loading reference 'https://tier.run/docs/$defs/plan': Unable to load schema from 'https://tier.run/docs/$defs/plan': Not Found. The requested location could not be found.
<!DOCTYPE html><!-- Last Published: Tue Nov 01 2022 23:11:41 GMT+0000 (Coordinated Universal Time) -->
<html data-wf-domain="webflow.tier.run" data-wf-page="..." data-wf-site="61e.(768)
```

![image](https://user-images.githubusercontent.com/33750251/199809527-4b89192f-2846-46d7-94e1-6a4ccca2d524.png)

### Steps to reproduce

Setup a `pricing.json` with the following in VSCode 1.73.0

```
{
  "$schema": "https://tier.run/docs/pricing.schema.json",
  "plans": {
    "plan:workshop@0": {
      "period": "@monthly",
      "features": {
        "feature:seat": {
          "aggregate": "perpetual",
          "tiers": [
            {
              "upto": 5,
              "base": 0
            },
            {
              "price": 9900
            }
          ]
        }
      }
    }
  }
}
```

### Are there any recent changes that introduced the issue?

N/A

### OS

Windows

### OS version

Windows 11

### Tier version

0.4.1

**Comment by isaacs** [comment]
Aha, VSCode handles relative links a bit differently than the schema validator I was using locally.

Updated to correct the problem, seems to work now. You might need to restart VSCode to pick up the updated schema.

**Comment by isaacs** [comment]
Wrote up how to wire this into nvim and vscode on our blog: https://blog.tier.run/validating-pricingjson-in-your-editor
