### ISSUE TITLE
FR: Health endpoint

### ISSUE THREAD

**Issue by gordalina** [tierrun/tier#148]
### What are you trying to do?

Trying to check whether Tier is in a healthy state, and currently, no API endpoints are useful for this.

### How should we solve this?

For example, Implement a dummy `/health` endpoint that returns 200/204.

### What is the impact of not solving this?

Can't run health checks in fly.io as they expect a 2xx response.

**Comment by bmizerany** [comment]
Thank you for the issue. Currently pull should return a 200 if tier is running properly. Until there is specific health check endpoint, would this be a stop gap?

**Comment by gordalina** [comment]
Yes

**Comment by bmizerany** [comment]
@gordalina Tier now has a `/v1/whoami` endpoint https://www.tier.run/docs/cli/whoami, which is now our recommended approach for health checks. It's lighter weight than `pull` while also ensuring the sidecar can reach Stripe successfully.

I'm going to close this issue, but please respond with any feedback and we can reopen it if needed.

**Comment by gordalina** [comment]
Working perfectly as [a health check](https://github.com/gordalina/fly-tier/commit/43bc11503d8e133618459e4d51c14985144399a2). Thank you

**Comment by bmizerany** [comment]
> Working perfectly as [a health check](https://github.com/gordalina/fly-tier/commit/43bc11503d8e133618459e4d51c14985144399a2). Thank you

Great!
