### ISSUE TITLE
lookupPhase raising stripe error

### ISSUE THREAD

**Issue by isaacs** [tierrun/tier#221]
### What is the issue?

Not sure if this is something in the node sdk doing something wrong, but when I try to hit `/v1/phase?org=...`, I'm getting a 500 error.  `TIER_DEBUG=1` in the env shows:

```
tierDEBUG: 127.0.0.1:57170 GET 127.0.0.1:17925
/v1/phase?org=org%3Acldcfqzff0002o2oe2ju8gl6v: lookupPhases: stripe:
acct_1MSTLm4Eht4IU5DC type:invalid_request_error message:Unrecognized request
URL (GET: /v1/subscription_schedules/). If you are trying to list objects,
remove the trailing slash. If you are trying to retrieve an object, make sure
you passed a valid (non-empty) identifier in your code. Please see
https://stripe.com/docs or we can help at https://support.stripe.com/.
```

### Steps to reproduce

Create an org, subscribe them to a plan, and then try to lookupPhase on that org.

### OS version

darwin

### Tier version

0.7.1   tier commit: d058cdac601f0764bd54f856de316ad068b5fcd4   go version: go1.20rc2

**Comment by isaacs** [comment]
CLI shows 500 as well:

```
$ tier phases org:cldcfqzff0002o2oe2ju8gl6v
tier: httpError{status:500 code:"internal_error" message:"Internal Server Error"}
```

Same error from `TIER_DEBUG=1`

**Comment by bmizerany** [comment]
I'm unable to reproduce it. What does `curl -d "customer=cus_123" -u $STRIPE_API_KEY: https://api.stripe.com/v1/subscriptions` return?

**Comment by bmizerany** [comment]
The output of that curl command would help confirm what I'm seeing, but I think I found the problem and am looking into it.

**Comment by isaacs** [comment]
This seems to only be a problem when subscribing via checkout.  Works fine when all subscriptions are through `/v1/subscribe`.

**Comment by bmizerany** [comment]
This happens with Checkout because creating a basic subscription is the best it can do.  Fancy things like schedules are not currently supported.

The bug here is: Tier is looking for schedules that do not exist because Checkout created none. I have found the offending lines of code and am working on a fix.
