### ISSUE TITLE
FR: YAML support

### ISSUE THREAD

**Issue by jgillich** [tierrun/tier#222]
### What are you trying to do?

JSON does not support comments, which can be useful. Therefore, it would be nice if tier added support for YAML.

### How should we solve this?

Replace the JSON with a YAML parser (YAML is a superset of JSON).

**Comment by bmizerany** [comment]
Pricing JSON supports HuJSON (https://github.com/tailscale/hujson) which supports comments. Does this help?

**Comment by jgillich** [comment]
Technically yes, but editors don't support this. So IMO support for YAML or TOML etc is still preferable.

**Comment by bmizerany** [comment]
We have no immediate plans to directly support YAML for "Pricing JSON" at this time.

If one prefers YAML, the very powerful and awesome https://github.com/cue-lang/cue can easily help. Amoung its many wonderful and powerful features, is its ability to convert yaml to json very easily:

```
~ % cat p.yml
plans:
  plan:free@0:
    features:
      feature:x:
        base: 1000
  plan:meatme@1:
    features:
      feature:m:
        tiers:
          - base: 10000
      feature:n:
        tiers:
          - base: 30000
      feature:o:
        tiers:
          - base: 60000
~ % cue export p.yml
{
    "plans": {
        "plan:free@0": {
            "features": {
                "feature:x": {
                    "base": 1000
                }
            }
        },
        "plan:meatme@1": {
            "features": {
                "feature:m": {
                    "tiers": [
                        {
                            "base": 10000
                        }
                    ]
                },
                "feature:n": {
                    "tiers": [
                        {
                            "base": 30000
                        }
                    ]
                },
                "feature:o": {
                    "tiers": [
                        {
                            "base": 60000
                        }
                    ]
                }
            }
        }
    }
}
```

Personally, I prefer using cue's language itself, and exporting to json. This example started as a `p.cue` file I keep around for testing. :)

If the conversion step is too undesirable, the HuJSON README provides a How To for adding editor support for it in VSCode, and I used their hints/tips to gain support for it in Vim.

I hope this helps. I'm closing this issue for now, but please reopen if you feel it is necessary.

**Comment by jgillich** [comment]
Understood, thanks. FWIW I know all the workarounds, I just think that the best UX would be to support a better format out of the box. But it's really not that important.

(As a fellow CUE lover, I'd consider that a good option as well 😉)
