### ISSUE TITLE
FR: Tax category

### ISSUE THREAD

**Issue by itsezc** [tierrun/tier#228]
### What are you trying to do?

Ability to set product tax category for each `plan` this is useful in Stripe (and potentially other payment providers) to determine the taxation rules.

### How should we solve this?

Add a `tax` property for each `plan`, where one could map it with a code of integers that is mapped to Stripe / other providers or a string i.e. `Software as a service (SaaS) - business use` which is mapped directly, although this could be an issue when dealing with other providers or multiple providers.

### What is the impact of not solving this?

Manually adding the tax information on the product on Stripe products.

**Comment by jevon** [comment]
#278

**Comment by bmizerany** [comment]
Closing. If #278 does fix this, please reopen.
