### ISSUE TITLE
tier push URL output link returns 'Price Not Found' in Stripe Dashboard

### ISSUE THREAD

**Issue by jgannon** [tierrun/tier#244]
### What is the issue?

I thought that since the 'tier push' command ran successfully (and outputted a Stripe Dashboard URL) that when I visited the URL I should have been shown the plan. 

Instead, the URL when visited told me: "Price Not Found"

### Steps to reproduce

1. Used Model Builder to create a pricing.json:

`johngannon@Johns-MacBook-Pro Downloads % cat pricing.json
{
  "plans": {
    "plan:regular@4": {
      "title": "Yearly Subscription",
      "interval": "@yearly",
      "features": {
        "feature:emailblast": {
          "title": "Email Blast",
          "base": 100000
        }
      }
    }
  }
}%   `

2. Pushed the plan (operation looked successful, based on the output)

`johngannon@Johns-MacBook-Pro Downloads % tier push pricing.json
ok	plan:regular@4	feature:emailblast	https://dashboard.stripe.com/acct_102xfJ2VniGt33G4/prices/price_1Mbcw62VniGt33G4QxG2CWBh	[created]`

3. Attempted to visit the provided URL from Step 3, and received a 'price not found' message in my Stripe Dashboard.  I was not expecting to receive that message given the 'tier pull' seemed to work and I was provided a link to visit.

I recorded a short Loom (1min) video of these steps as I executed them (slightly different pricing.json file in that I changed the word 'regular' to 'foo'). [Video is linked here.](https://www.loom.com/share/e0439c03493e4a4b815489df772f9992)

### OS

macOS

### OS version

Ventura 13.2

### Tier version

0.7.1

**Comment by bmizerany** [comment]
@jgannon Stripe will not error if you do not have access to a resource you do not have access to and does not make it super obvious which account you're logged into when attempting to view the resource. 

Do you mind confirming the account Tier is connected to (see "tier whoami") is the one in the dashboard you're looking at (see top left account icon)

**Comment by bmizerany** [comment]
Would you also mind trying "Developer" mode in Stripe. I didn't see in your loom that the --live flag was used, and so Tier pushed to Test Mode in Stripe using the test key.

**Comment by jgannon** [comment]
Thanks for the followup @bmizerany -- here's what I see from the tier whoami output:

```shell
johngannon@Johns-MacBook-Pro Downloads % tier whoami
ID:         acct_102xfJ2VniGt33G4
KeySource:  /Users/johngannon/.config/tier/config.json
Isolated:   false
Email:      
Created:    2013-11-17T23:49:55-05:00
URL:        https://dashboard.stripe.com/acct_102xfJ2VniGt33G4
```

And here's a screenshot from Stripe, which shows the ID matches:

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/1332872/219050769-081f9ea9-bcde-4289-8eb6-f7cafb89fd7d.png">

I flipped on Test Mode in Stripe Dashboard and then ran the push again, with a new pricing.json:

```shell
johngannon@Johns-MacBook-Pro Downloads % tier push pricing.json
ok	plan:wedsmorning@5	feature:newemailblast	https://dashboard.stripe.com/acct_102xfJ2VniGt33G4/prices/price_1MblvZ2VniGt33G4giceDWxI	[created]
johngannon@Johns-MacBook-Pro Downloads % cat pricing.json
{
  "plans": {
    "plan:wedsmorning@5": {
      "title": "Weds Subscription",
      "interval": "@yearly",
      "features": {
        "feature:newemailblast": {
          "title": "New Email Blast",
          "base": 100000
        }
      }
    }
  }
}
```

When I look at Stripe logs I see that the POST returned 200 this morning (right now) and also last night, when I originally filed the issue (and before I flipped on Test Mode). Here's what I saw in the logs just now. I've highlighted what I believe to be the successful results of the push:

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/1332872/219056488-d189a3bd-e009-4569-a3c9-fa58364dd0ee.png">


Still getting the price not found page, though, when I try to visit it:

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/1332872/219056180-947723a3-097b-4927-9f72-0b66d37bad4e.png">

**Comment by bmizerany** [comment]
Thank you for the detailed response! It has not gone unnoticed. I can look into this tomorrow and will get back to you.

**Comment by bmizerany** [comment]
@jgannon If you click on the "Products" tab, do you see your product?

**Comment by bmizerany** [comment]
> Still getting the price not found page, though, when I try to visit it:
> 
> <img alt="image" width="1250" src="https://user-images.githubusercontent.com/1332872/219056180-947723a3-097b-4927-9f72-0b66d37bad4e.png">

It looks like this is in live mode. I don't see `/test/` in the URL. Do you mind confirming?

**Comment by bmizerany** [comment]
@jgannon Any chance you've had a chance to check if changing the URL to a test URL helps?

**Comment by bmizerany** [comment]
@jgannon I finally saw the issue and have a fix incoming! It should land in main shortly.
