### ISSUE TITLE
Sort plans by attribute(e.g. access price ASC) instead of alphabetically

### ISSUE THREAD

**Issue by jevon** [tierrun/tier#290]
### Discussed in https://github.com/tierrun/tier/discussions/288

<div type='discussions-op-text'>

<sup>Originally posted by **DesignsByVanessa** April  4, 2023</sup>
Hi, 

Just found tier yesterday. Great concept, it definitely is a time saver and eliminates a lot of opportunity for human error. 

The return object currently sorts by alphabetical, when most landing pages would want it by base price.

For example, if a user has 4 plans, it would currently sort as:
Enterprise -> Free -> Growth -> Starter

This should almost always be:
Free -> Starter -> Growth -> Enterprise

Is there a way to do this already, or is it in the queue?

It would be nice to have these returned ready-to-use by the node SDK instead of having to re-sort objects in the website code.

![image](https://user-images.githubusercontent.com/124464640/229766199-47575562-e6a8-46dc-8aba-ebe77dc65cf4.png)

![image](https://user-images.githubusercontent.com/124464640/229766498-89a2317a-c053-40ec-a60b-a1c6c8bcd96d.png)

It's very likely I missed a param that does this or am doing something wrong.

Greatly appreciate any advice, even if it is "Sort it in the Web App." or use the something numeric(not as pleasant to humans) like "100 200 300 400" for the plan name.

</div>

**Comment by isaacs** [comment]
https://github.com/tierrun/tier/discussions/288#discussioncomment-5565586

**Comment by PatrickHeneise** [comment]
@isaacs it seems discussions have been disabled, so I'm not able to see how this was resolved.
