### ISSUE TITLE
FR:  Admin Endpoint to Query all Organizations by specific filter

### ISSUE THREAD

**Issue by Makisuo** [tierrun/tier#292]
### What are you trying to do?

I would like to be able to build a admin overview to monitor plan usage, subscriptions and metering.
I want to be able to all organizations query for specific plans or features. 

### How should we solve this?

A new sdk and cli endpoint 

### What is the impact of not solving this?

RIght now there is no way for me to build this without this feature.

**Comment by bmizerany** [comment]
Hi @Makisuo,

Thanks for reaching out with your question. While Tier currently doesn't have plans to add analytics, we do provide a `tier.feature` metadata key on all prices created, which can be utilized for filtering and rolling up data.

You can achieve your desired functionality by using the Stripe API directly. To do this, you can refer to the following documentation on listing invoices: https://stripe.com/docs/api/invoices/list. This should help you with manual rollups.

Alternatively, you might want to consider exploring third-party Stripe tools, as some of them may support metadata and provide a no-code solution for your needs. Some can be found here: https://marketplace.stripe.com/categories/data_and_analytics

I hope this helps! Let us know if you have any other questions or need further assistance.

I'm closing this issue, but please reopen it if you believe I'm misunderstanding your request.
