### ISSUE TITLE
tier.run not compatible with latest golang.org/x/exp package

### ISSUE THREAD

**Issue by pkwarren** [tierrun/tier#306]
### What is the issue?

A recent change to mirror changes coming in Go 1.21 to the the golang.org/x/exp package broke compatibility with tier.run. The build is failing with:

```
$ go build ./...                          
# tier.run/refs
refs/refs.go:286:22: type func(a FeaturePlan, b FeaturePlan) bool of func(a, b FeaturePlan) bool {…} does not match inferred type func(a FeaturePlan, b FeaturePlan) int for func(a E, b E) int
```

The `slices.SortFunc` function now requires that the function return int, not bool.

### Steps to reproduce

```
$ go get -u golang.org/x/exp
$ go mod tidy
$ go build ./...
```

### Are there any recent changes that introduced the issue?

https://cs.opensource.google/go/x/exp/+/302865e7556b4ae5de27248ce625d443ef4ad3ed

### OS

macOS

**Comment by bmizerany** [comment]
Thank you for the report. I'll take a look at this.

**Comment by bmizerany** [comment]
How is this affecting you right now? I'm able to build with the current 1.21rc3 just fine.

**Comment by pkwarren** [comment]
We are pulling in tier.run along with other dependencies which are attempting to upgrade the x/exp package. In the meantime we are having to hold off upgrading those packages until tier.run module is compatible with the new version. 

Not a huge deal and not a bug per-se in tier.run but it would be nice to be able to keep up to date with all our dependencies.

**Comment by mfridman** [comment]
With go1.21 released should probably use the standard lib version of slices instead of x/exp/slices

https://pkg.go.dev/slices

Fwiw the specific breaking change was https://go-review.googlesource.com/c/exp/+/511895

Until this repository bumps golang.org/x/exp/slices or switches to the standard lib, we're stuck pinning to an older supported version of /x/exp/slices
