### ISSUE TITLE
plan creation through tier CLI

### ISSUE THREAD

**Issue by VimannyuC11** [tierrun/tier#308]
### What is the issue?

When using the Tier CLI and Model Builder to create plans with multiple features, my expectation is to generate 3 unique plans, each containing the same set of features. However, after pushing the plans through the CLI, I am observing 9 different plans in the Stripe dashboard instead of the expected 3 plans with identical features.

### OS version

Windows 10

### Tier version

0.12.0-dev

**Comment by jevon** [comment]
This is expected behaviour. Tier uses the concept of Feature Plans to manage entitlements and any associated data (meters). eg. feature:foo@plan:bar@1 will generate a Product and Price in Stripe.

**Comment by VimannyuC11** [comment]
Okay is there any other alternative according to you which will suffice my subscription model condition in tier ? @jevon

**Comment by jevon** [comment]
> Okay is there any other alternative according to you which will suffice my subscription model condition in tier ? @jevon

As long as you use the Tier SDK, it shouldn't matter to you, Tier will handle everything.
