### ISSUE TITLE
cmd/tier: pull halts upon encountering a Stripe price without Tier meta

### ISSUE THREAD

**Issue by jevon** [tierrun/tier#6]
After a successful push, cannot *tier pull*

> jevon@Jevons-MacBook-Air tierx % go run github.com/tierrun/tierx/cmd/tier@tierconnect pull               
> tier: missing metadata: tier.plan
> exit status 1

**Comment by bmizerany** [comment]
Great find @jevon. The intended behavior was to ignore non-tier prices in Stripe. Working on this now.
