### ISSUE TITLE
make `tier serve` respond to --verbose flag

### ISSUE THREAD

**Issue by isaacs** [tierrun/tier#90]
Would be nice to have a way for the sidecar to dump the requests it gets for logging and debugging purposes.

**Comment by bmizerany** [comment]
It's there. Try `tier -v serve`. It may not be as verbose as you like, however, you can also set `STRIPE_DEBUG=1` and get a the input and output for tier <> Stripe.

Both `tier -v` and `STRIPE_DEBUG` must be used together for the env var to work.
