### ISSUE TITLE
FR: change "features" in pricing.json to "entitlements"

### ISSUE THREAD

**Issue by bmizerany** [tierrun/tier#95]
### What are you trying to do?

Make tier look less like we're a full-blown feature flag management system, but instead convey better that we're holding the truth about what the customer is paying for and expects to be able to do and under what conditions were agreed upon (e.g. price, paying on time, etc).

### How should we solve this?

Rename `.plans[].features` to `.plans[].entitlements`

### What is the impact of not solving this?

Possibly continued confusion.

**Comment by isaacs** [comment]
I am ok with this change.  Will line up docs to reflect asap.

**Comment by bmizerany** [comment]
I think this needs a little more thought. Punting for now and happy to reopen at some point soon.
